In [6]:
def primeornot(a):
    c=0
    for i in range(1,a+1):
        if (a%1==0):
            c=c+1
    if (c==2):
        print('prime')
    else:
        print('not prime')
    

In [8]:
a=int(input())
primeornot(a)


87
not prime


In [10]:
lb=1
ub=100
def primerange(lb,ub):
    for i in range (1,ub+1):
        if primeornot(a):
            print(i,end =' ')
    

In [ ]:
def priomes(n):
    if n<2:
        print('not a prime')
        for i in range (2,n//2):
            if n%i==0
            return 0
        return 1v 
            

# MAPS

In [11]:
dir(str)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',


In [13]:
list(map(str,input()))

pyton


['p', 'y', 't', 'o', 'n']

In [14]:
def add(n):
    return n+n

In [15]:
add(5)

10

In [16]:
list(map(add,[4,5,6,1]))

[8, 10, 12, 2]

In [18]:
def power(n):
    return n**n

In [19]:
list(map(power,[4,5,6,1]))

[256, 3125, 46656, 1]

In [23]:
def sqrt(n):
    return n*n

In [24]:
list(map(sqrt,[4,5,6,1]))

[16, 25, 36, 1]

In [25]:
list(map(str,[4,5,6,1]))

['4', '5', '6', '1']

In [26]:
list(map(int,['4','5','6','1']))

[4, 5, 6, 1]

# filter

In [27]:
l=[1,2,'a','c','d']
def isdigit(n):
    n=str(n)
    if n.isdigit():
        return 1
    return 0

In [29]:
list(filter(isdigit,l))

[1, 2]

In [46]:
l=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
def prime(n):
    if n<2:
        return 0
    for i in range(2,n//2+1):
        if n%i == 0:
            return 0
    return 1
def odd(n):
    if n%2!=0:
        return True
    return False
def even(n):
    if n%2==0:
        return True
    return False


In [47]:
list(filter(odd,l))

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [48]:
list(filter(even,l))

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [49]:
list(filter(prime,l))

[2, 3, 5, 7, 11, 13, 17, 19]

# lamdas

In [54]:
 h= lambda x :x%2!=0
list(filter(h,[1,2,3,4,5]))

[1, 3, 5]

In [57]:
from random import randint as r
for i in range(1,10+1):
    print (r(1,25))

18
25
8
15
21
16
24
22
1
6


In [69]:
m1=[r(1,35) for i in range (1,11)]
m2=[r(1,35) for i in range (1,11)]
m3=[r(1,35) for i in range (1,11)]
print(m1)
print(m2)
print(m3)

[8, 28, 15, 28, 11, 18, 13, 1, 5, 6]
[30, 32, 18, 27, 4, 35, 22, 1, 15, 24]
[33, 7, 21, 4, 29, 4, 26, 31, 4, 12]


In [67]:
a1=list(map(lambda x,y:x+y//2,m1,m2))
print(a1)


[41, 16, 25, 13, 10, 33, 32, 23, 39, 19]


In [70]:
a2=list(map(lambda x,y,z:x+y+z//3,m1,m2,m3))

In [75]:
print(a2)

[49, 62, 40, 56, 24, 54, 43, 12, 21, 34]


In [76]:
list(filter(lambda x:x<10,a2))

[]

In [79]:
list(filter(lambda x:x>20,a1))

[41, 25, 33, 32, 23, 39]

In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5]
a1=np.array(l)
l

[1, 2, 3, 4, 5]

In [3]:
a1

array([1, 2, 3, 4, 5])

In [4]:
print(a1)

[1 2 3 4 5]


In [7]:
l=[[1,2,3,4],[1,2,3,4],[5,8,6,39]]
a1=np.array(l)
print(a1)

[[ 1  2  3  4]
 [ 1  2  3  4]
 [ 5  8  6 39]]


In [9]:
l=[[1,2,3,4],[1,2,3,4]]
a1=np.array(l)
print(a1)

[[1 2 3 4]
 [1 2 3 4]]


In [15]:
a=np.arange(10).reshape(2,5)
print (a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [11]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [18]:
a=np.arange(6).reshape(2,3)
b=np.arange(3,9).reshape(2,3)
c=np.arange(2,8).reshape(2,3)
d=np.arange(1,7).reshape(2,3)

In [19]:
print(a)
print(b)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[3 4 5]
 [6 7 8]]
[[2 3 4]
 [5 6 7]]
[[1 2 3]
 [4 5 6]]


In [20]:
a+b+c

array([[ 5,  8, 11],
       [14, 17, 20]])

In [21]:
a-b

array([[-3, -3, -3],
       [-3, -3, -3]])

In [23]:
a*b*c

array([[  0,  12,  40],
       [ 90, 168, 280]])

In [25]:
a//b

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)